name: Git Bridge (PR Bot)
slug: git_bridge
description: Secure GitHub PR bridge for ChatGPT Actions
version: "1.0.2"
url: https://github.com/VoteForPedro83/home-assistant-addons
arch:
  - amd64

startup: services
boot: auto

ports:
  8000/tcp: 8000

webui: "http://[HOST]:[PORT:8000]"

options: {}
schema: {}
