name: "Git Bridge (PR Bot)"
slug: "git_bridge"
description: "Secure GitHub PR bridge for ChatGPT Actions"
version: "1.0.7"
url: "https://github.com/VoteForPedro83/home-assistant-addons"

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

startup: services
boot: auto
init: false
protected: true

ports:
  8000/tcp: 8000

webui: "http://[HOST]:[PORT:8000]"

options: {}
schema: {}
