name: Git Bridge (PR Bot)
slug: git_bridge
version: "1.0.2"
description: Secure GitHub PR bridge for ChatGPT Actions
url: https://github.com/VoteForPedro83/home-assistant-addons

startup: application
boot: auto

arch:
  - amd64

ports:
  8099/tcp: 8099

webui: "http://[HOST]:[PORT:8099]/docs"

options: {}
schema: {}
